name: Build Examples

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable # 或者指定具体版本，如 '1.67.0'
        override: true

    - name: Build example
      run: cargo build --example quantized --release

    - name: Create release directory
      run: mkdir -p release

    - name: Copy binary to release directory
      run: cp target/release/examples/quantized release/
