name: Build and Release Examples

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable # 或者指定具体版本，如 '1.67.0'
        override: true

    - name: Build example
      run: cargo build --example quantized --release

    - name: Create release directory
      run: mkdir -p release

    - name: Copy binary to release directory
      run: cp target/release/examples/quantized release/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v1.0.0 # 根据需要设定版本号
        release_name: Release v1.0.0
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0 # 与上面的 tag_name 保持一致
        files: release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
